"""add created_at, updated_at in todos

Revision ID: bc34075396d4
Revises: 
Create Date: 2025-04-11 13:39:27.412885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc34075396d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', postgresql.TIMESTAMP()))
    op.execute("UPDATE todos SET created_at = NOW()")
    op.alter_column('todos', 'created_at', nullable=False)
    op.add_column('todos', sa.Column('updated_at', postgresql.TIMESTAMP()))
    op.execute("UPDATE todos SET updated_at = NOW()")
    op.alter_column('todos', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
