"""add created_at, updated_at in user

Revision ID: fcf3d3ab564c
Revises: bc34075396d4
Create Date: 2025-04-11 13:48:49.497247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcf3d3ab564c'
down_revision: Union[str, None] = 'bc34075396d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP()))
    op.execute("UPDATE users SET created_at = NOW()")
    op.alter_column('users', 'created_at', nullable=False)
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP()))
    op.execute("UPDATE users SET updated_at = NOW()")
    op.alter_column('users', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
